### ISSUE TITLE
Move from Travis-CI to GitHub Actions

### ISSUE THREAD

**Issue by BenjamenMeyer** [vegastrike/Assets-Production#43]
This is a the Assets Production version of 
https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/382.

**Comment by BenjamenMeyer** [comment]
Started porting over the functionality from the engine for master. Once that's ported to master we can then port it to 0.7.x.

**Comment by stephengtuggy** [comment]
We never finished this on master, did we? 0.7.x has more recent changes than master does, on the GH-Actions-related files.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy not sure off hand, an audit is easy enough to do

**Comment by stephengtuggy** [comment]
I did an audit. The files on master still reference `TRAVIS_TAG` and `TRAVIS_OS`. We'll need to fix that.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy thanks. I'll put together a PR tonight.

**Comment by stephengtuggy** [comment]
@BenjamenMeyer Sounds good.

**Comment by BenjamenMeyer** [comment]
@stephengtuggy sorry for the delay - https://github.com/vegastrike/Assets-Production/pull/54

**Comment by Loki1950** [comment]
Life happens just reviewed #54
